# @format

version: 0.2
phases:
  install:
    commands:
      - echo Building for production environment
      - echo Entered the install phase...
      - npm ci
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
  name: as3six-react-$(date +%Y-%m-%d) \
  base-directory: dist/
